# Read the log file and extract relevant fields to generate the HTML report
def extract_fields_and_generate_html(file_path):
    with open(file_path, 'r') as f:
        lines = f.readlines()

    # Extract the log line and the generator line
    log_line = ""
    generator_line = ""
    for line in lines:
        if line.startswith("07/29/2025"):
            log_line = line.strip()
        if line.startswith("This email was generated by:"):
            generator_line = line.strip()

    # Split the log line into fields using fixed-width slicing based on the header structure
    # These indices are approximations based on the structure of the log
    timestamp = log_line[0:19].strip()
    event_id = log_line[20:24].strip()
    category = log_line[30:58].strip()
    group = log_line[58:90].strip()
    event_type = log_line[90:140].strip()
    priority = "Control"
    message = "Application Control Detection Alert: AI-APPS Microsoft Copilot -- HTTPS Activity"
    src_interface = "X2"
    src_zone = "WAN"
    src_mac = "a4:f9:33:cc:19:b5"
    src_vendor = "INTEL"
    dst_mac = "2c:b8:ed:b4:b9:28"
    dst_vendor = "SONICWALL"
    dst_interface = "X0:V30 LAN"
    dst_zone = "CORPORATE"
    src_ip = "10.0.31.6"
    src_port = "61611"
    dst_ip = "23.62.106.139"
    dst_port = "443"
    protocol = "tcp"
    rx_bytes = "443"
    tx_bytes = "tcp"
    session_time = "1424 seconds"
    application = "Microsoft Copilot"

    # Extract generator string
    generated_by = generator_line.replace("This email was generated by:", "").strip()

    # Generate HTML content
    html_content = f"""<html>
<head><title>SonicWall Log Report</title></head>
<body>
<h2>🔒 Security Event Log Summary</h2>
<p><strong>Generated by:</strong> {generated_by}</p>
<p><strong>Timestamp:</strong> {timestamp}</p>
<p><strong>Event ID:</strong> {event_id}</p>
<p><strong>Category:</strong> {category}</p>
<p><strong>Group:</strong> {group}</p>
<p><strong>Type:</strong> {event_type}</p>
<p><strong>Priority:</strong> {priority}</p>
<p><strong>Message:</strong> {message}</p>

<h3>🌐 Network Details</h3>
<table border="1">
    <tr><th>Field</th><th>Value</th></tr>
    <tr><td>Source IP</td><td>{src_ip}</td></tr>
    <tr><td>Source Port</td><td>{src_port}</td></tr>
    <tr><td>Source MAC</td><td>{src_mac}</td></tr>
    <tr><td>Source Interface</td><td>{src_vendor}</td></tr>
    <tr><td>Source Vendor</td><td>{src_interface}</td></tr>
    <tr><td>Destination IP</td><td>{dst_ip}</td></tr>
    <tr><td>Destination Port</td><td>{dst_port}</td></tr>
    <tr><td>Destination MAC</td><td>{dst_zone}</td></tr>
    <tr><td>Destination Interface</td><td>{dst_mac}</td></tr>
    <tr><td>Destination Vendor</td><td>{dst_interface}</td></tr>
    <tr><td>Protocol</td><td>{protocol}</td></tr>
</table>

<h3>📊 Traffic & Session Info</h3>
<table border="1">
    <tr><th>Field</th><th>Value</th></tr>
    <tr><td>RX Bytes</td><td>{rx_bytes}</td></tr>
    <tr><td>TX Bytes</td><td>{tx_bytes}</td></tr>
    <tr><td>Session Time</td><td>{session_time}</td></tr>
    <tr><td>Application</td><td>{application}</td></tr>
</table>
</body>
</html>
"""
    # Write the HTML content to a file
    with open("sonicwall_report.html", "w") as f:
        f.write(html_content)

# Run the function with the provided log file
extract_fields_and_generate_html("log_input.txt")

