
import re

# Read the log file
with open("sonicwall_log.txt", "r") as file:
    content = file.read()

# Extract the log line and the generator line
log_line = next(line for line in content.splitlines() if re.match(r"\d{2}/\d{2}/\d{4}", line))
generator_line = next(line for line in content.splitlines() if "This email was generated by" in line)

# Split the log line into fields
fields = log_line.split()

# Extract values from the log line
timestamp = f"{fields[0]} {fields[1]}"
event_id = fields[2]
category = " ".join(fields[3:5])
group = " ".join(fields[5:7])
event_type = " ".join(fields[7:13])
priority = fields[13]
src_mac = fields[16]
src_vendor = fields[17]
src_interface = fields[18]
dst_mac = fields[19]
dst_vendor = fields[20]
dst_interface = fields[21]
src_ip = fields[24]
src_port = fields[25]
dst_ip = fields[28]
dst_port = fields[29]
protocol = fields[30]
rx_bytes = fields[31]
tx_bytes = fields[32]
session_time = fields[34]
application = "Microsoft Copilot"
message = " ".join(fields[39:])  # Message starts from index 39

# Extract generator info
generated_by = generator_line.split("This email was generated by:")[1].strip()

# Generate HTML content
html_content = f"""<html>
<head><title>SonicWall Log Report</title></head>
<body>
<h2>🔒 Security Event Log Summary</h2>
<p><strong>Generated by:</strong> {generated_by}</p>
<p><strong>Timestamp:</strong> {timestamp}</p>
<p><strong>Event ID:</strong> {event_id}</p>
<p><strong>Category:</strong> {category}</p>
<p><strong>Group:</strong> {group}</p>
<p><strong>Type:</strong> {event_type}</p>
<p><strong>Priority:</strong> {priority}</p>
<p><strong>Message:</strong> {message}</p>

<h3>🌐 Network Details</h3>
<table border="1">
    <tr><th>Field</th><th>Value</th></tr>
    <tr><td>Source IP</td><td>{src_interface}</td></tr>
    <tr><td>Source Port</td><td>WAN</td></tr>
    <tr><td>Source MAC</td><td>Message</td></tr>
    <tr><td>Source Interface</td><td>{src_mac} ({src_vendor})</td></tr>
    <tr><td>Source Vendor</td><td>StringAlert 2048</td></tr>
    <tr><td>Destination IP</td><td>{dst_ip}</td></tr>
    <tr><td>Destination Port</td><td>{dst_port}</td></tr>
    <tr><td>Destination MAC</td><td>{dst_vendor}</td></tr>
    <tr><td>Destination Interface</td><td>{dst_mac} ({dst_interface})</td></tr>
    <tr><td>Destination Vendor</td><td>X0:V30 LAN</td></tr>
    <tr><td>Protocol</td><td>{protocol}</td></tr>
</table>

<h3>📊 Traffic & Session Info</h3>
<table border="1">
    <tr><th>Field</th><th>Value</th></tr>
    <tr><td>RX Bytes</td><td>{rx_bytes}</td></tr>
    <tr><td>TX Bytes</td><td>{tx_bytes}</td></tr>
    <tr><td>Session Time</td><td>{session_time} seconds</td></tr>
    <tr><td>Application</td><td>{application}</td></tr>
</table>
</body>
</html>
"""

# Save the HTML content to a file
with open("sonicwall_report.html", "w") as html_file:
    html_file.write(html_content)

print("HTML report has been generated and saved as 'sonicwall_report.html'.")
